from __future__ import annotations

from typing import Protocol


class SpiBus(Protocol):
    def write(self, data: bytes) -> None: ...

    def close(self) -> None: ...


class GpioBus(Protocol):
    def setup_output(self, pin: int) -> None: ...

    def setup_input(self, pin: int) -> None: ...

    def write(self, pin: int, value: int) -> None: ...

    def read(self, pin: int) -> int: ...

    def cleanup(self) -> None: ...
